### ISSUE TITLE
Private repo access.

### ISSUE THREAD

**Issue by tikotzky** [volta-net/feedback#21]
I subscribed but still dont have access to private repos. Is there anything I need to do to view private repos?

**Comment by benjamincanac** [comment]
Hello @tikotzky,

Indeed, it seems that your organization encountered a `Rate limit` error during its import which prevented the sync of the collaborators for some repositories. We deployed a patch today to prevent this from happening again in the future.

I've manually re-synced all your repositories and you should now have access to your whole organization.

Let me know if this is not the case.

**Comment by tikotzky** [comment]
Thanks! I'm still getting prompted to sign up when trying to access a private repo even though when I click through it shows that im already subscribed

**Comment by benjamincanac** [comment]
Can you refresh the app? It seems we had a webhook issue during your payment. Sorry for the inconvenience!

**Comment by tikotzky** [comment]
Thanks! I now have access to private repos, though I'm still seeing errors relating to the rate limit...

**Comment by benjamincanac** [comment]
Your repositories have been imported successfully, you shouldn't see any error anymore.
You can always launch a full re-sync of your repositories if you're missing some data by going to the repository settings, `GitHub` tab, selecting all the entities (Issues, Pull Requests, Tags, Releases and Labels) and clicking on the `Sync` button.

![CleanShot 2022-11-09 at 10.50.23@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2022_11_09_at_10_50_23_2x_370c23d312.png)

Let me know if you encounter any other issue.

**Comment by tikotzky** [comment]
Thanks!
